data:
    input_size: 512
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 16

model:
    type: "simple"
    ch: 512
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    dropout: 0.1
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    c_noise : True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 32
    n_epochs: 30000
    n_iters: 5000000
    snapshot_freq: 3000
    validation_freq: 2000

sampling:
    batch_size: 20
    last_only: True

optim:
    weight_decay: 0.000
    lr_decay: 0.998
    optimizer: "Adam"
    lr: 0.0001
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0